openapi: 3.0.3
info:
  version: 0.0.1
  title: REST Intro Sample Application
  description: A small sample API to grasp the basics of the OpenAPI Specification
servers:
  - url: http://localhost:8080

paths:
  # https://swagger.io/specification/#paths-object
  /api/ping:
    # https://swagger.io/specification/#path-item-object
    get:
      # https://swagger.io/specification/#operation-object
      summary: Returns a simple pong to check if the service is alive
      operationId: ping
      responses:
        200:
          # https://swagger.io/specification/#response-object
          description: Simply the string `pong`
          content:
            text/plain:
              schema:
                type: string
                example: pong
                # just one constant value (usually an enum contains multiple values)
                enum:
                  - pong
        default:
          description: A sample error mainly here to give a sample on how to use components
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SampleError"
  /api/article:
    get:
      responses:
        200:
          description: got some articles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ArticleDto"
    post:
      responses:
        200:
          description: made a new article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArticleDto"
        400:
          description: no misinformation is allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoMisinformationError"
    # the endpoint PATCH /api/article does not exist, PATCH /api/article/api/article/{id} would exist however
    # the same holds for DELETE, I guess this wasn't tested
    patch:
      responses:
        200:
          description: updated an article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArticleDto"
        400:
          description: no misinformation is allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoMisinformationError"
    delete:
      responses:
        204:
          description: deleted an article

# components contain reusable definitions
# https://swagger.io/specification/#components-object
components:
  schemas:
    ArticleDto:
      # TODO: add description
      properties:
        id:
          # TODO: add examples to all properties
          # maybe also readOnly: true
          type: integer
        headline:
          type: string
        content:
          type: string
        tags:
          type: array
          items:
            type: string
            example: politics
        likes:
          type: integer
        dislikes:
          type: integer
        posted:
          type: string
          format: date
      # notice that no validation is applied at all to articles: it is allowe to have no headline for example
    NoMisinformationError:
      # this is wrong: spring will convert it to a format similar to SampleError on the wire
      properties:
        message:
          type: string
    SampleError:
      description: Sample springboot error
      properties:
        timestamp:
          type: string
          example: 2022-02-28T14:13:56.466
          format: date-time
        status:
          type: number
          example: 404
        error:
          type: string
          example: Not Found
        path:
          type: string
          example: /api/nonexistent
          pattern: "/.+"
