# the IntelliJ build in HTTP client, read a description at
# https://www.vojtechruzicka.com/intellij-idea-tips-tricks-testing-restful-web-services/
# or the official
# https://www.jetbrains.com/help/idea/exploring-http-syntax.html

POST http://localhost:8080/api/ponies
Content-Type: application/json
User-Agent: fuu-bar

{
  "name": "Le Brun",
  "color": "brown"
}

###
